### ISSUE TITLE
Dataset used.

### ISSUE THREAD

**Issue by glacaria** [NihalPratap/Stock-Market-Prediction-with-LSTM#1]
Hi Nihal. 
I just had a look at your code and it looks great. I tried to run it but then got an error since you didn't add the price.csv file. Can you do so please? I would really appretiate that.

**Comment by NihalPratap** [comment]
Hi Glacaria,

I have uploaded the file onto the repository.

**Comment by glacaria** [comment]
Ok thanks Nihal, i really appreciate it. Can i get your email so that I can communicate with you? I'm new to machine learning and there are some areas of your code i'll need some help understanding

**Comment by NihalPratap** [comment]
You can find my email on my profile.
